apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: my_nginx:latest
        imagePullPolicy: "Never"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /nginx_status
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 3
          periodSeconds: 3
      hostname: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations: 
    metallb.universe.tf/allow-shared-ip: nginx

spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: nginx
  type: LoadBalancer

