apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: my_nginx
        imagePullPolicy: "Never"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: nginx
  type: LoadBalancer