apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: my_mariadb
        imagePullPolicy: "Never"
        ports:
        - name: https
          containerPort: 3306
      hostname: mariadb

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  annotations: 
    metallb.universe.tf/allow-shared-ip : nginx
spec:
  ports:
  - name: https
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mariadb
  type: ClusterIP

