apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deploy
spec:
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: my_influxdb:latest
        imagePullPolicy: "Never"
        ports:
        - name: api
          containerPort: 8086
        volumeMounts:
        - name: telegraf-endpoint
          mountPath: "/var/run/docker.sock"
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
      volumes:
      - name: telegraf-endpoint
        hostPath:
          path: /var/run/docker.sock
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pvc
      hostname: influxdb

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb
  name: influxdb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  ports:
  - name: api
    port: 8086
    targetPort: 8086
    protocol: TCP
  selector:
    app: influxdb
  type: ClusterIP

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf-account
  labels:
    app: influxdb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: telegraf-account
  namespace: default

